### ISSUE TITLE
Convert loader modules to importers

### ISSUE THREAD

**Issue by TheMadDodger** [TheMadDodger/Glory#273]
- [x] SDL Image Importer (#277)
- [x] ASSIMP Model Importer (#279)
- [x] Material importer (#280)
- [x] Material instance importer (#281)
- [x] Texture importer (#282)
- [x] Prefab importer (#283)
